# Generated by Django 5.1 on 2024-08-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="chat_room",),
        migrations.RemoveField(model_name="message", name="user",),
        migrations.DeleteModel(name="ChatRoom",),
        migrations.DeleteModel(name="Message",),
    ]
