# Generated by Django 5.1 on 2024-08-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_chat_room_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='message_type',
            field=models.CharField(default='text_message', max_length=100),
        ),
    ]
