# Generated by Django 5.1 on 2024-08-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messages_is_read_messages_is_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatrooms'),
        ),
    ]
