# Generated by Django 5.1 on 2024-08-30 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_messages_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.chatrooms'),
        ),
    ]
