# Generated by Django 5.0.6 on 2024-08-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_classroom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_no'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
